# Generated by Django 4.2.1 on 2023-07-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0002_menu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
