# Generated by Django 4.2.3 on 2023-07-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0003_alter_person_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Romes_Model_API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('No_Beds', models.IntegerField()),
            ],
        ),
    ]
