# Generated by Django 4.2.3 on 2023-07-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0010_alter_romes_model_api_desk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
