# Generated by Django 4.2.3 on 2023-07-23 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tester', '0011_person_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='romes_model_api',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Tester.person_room'),
        ),
    ]
