# Generated by Django 4.2.4 on 2023-08-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Seoudi_Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Seoudi_Orders.customer'),
        ),
        migrations.AddField(
            model_name='order_details',
            name='order_items',
            field=models.ManyToManyField(to='Seoudi_Orders.order_item'),
        ),
    ]
