# Generated by Django 4.2.4 on 2023-08-06 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Seoudi_Orders', '0002_order_details_customer_order_details_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
