# Generated by Django 4.2.4 on 2023-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seoudi_Orders', '0004_remove_order_details_date_alter_order_details_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
