# Generated by Django 4.2.4 on 2023-08-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seoudi_Orders', '0005_order_details_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='status',
            field=models.CharField(choices=[('case1', '11'), ('case2', '22'), ('case3', '33')], default='option1', max_length=10),
        ),
    ]
