# Generated by Django 4.2.3 on 2023-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fixer', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORderITer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Componest', models.CharField(max_length=255)),
                ('inverntory', models.SmallIntegerField()),
            ],
        ),
    ]
