# Generated by Django 4.2.3 on 2023-07-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fixer', '0004_category_items_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='Category',
        ),
    ]
