# Generated by Django 4.2.3 on 2023-07-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fixer', '0005_rename_category_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Fixer.category'),
        ),
    ]
