# Generated by Django 4.2.3 on 2023-07-21 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fixer', '0006_alter_items_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ORderITer',
        ),
    ]
