# Generated by Django 4.2.3 on 2023-07-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fixer', '0012_category_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
