# Generated by Django 4.2.3 on 2023-07-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fixer', '0020_items_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
